definitions:
  domain.AccountCreatorRequest:
    properties:
      cpf:
        type: string
      name:
        type: string
      secret:
        type: string
    type: object
  domain.AccountCreatorResponse:
    properties:
      id:
        type: string
    type: object
info:
  contact: {}
paths:
  /accounts:
    post:
      consumes:
      - application/json
      description: Create new Account in case 'cpf' doesn't exists yet
      parameters:
      - description: Account request
        in: body
        name: AccountRequest
        required: true
        schema:
          $ref: '#/definitions/domain.AccountCreatorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.AccountCreatorResponse'
      summary: Create Account
      tags:
      - Account
swagger: "2.0"
