definitions:
  domain.Account:
    properties:
      cpf:
        type: string
      created_at:
        type: string
      id:
        type: string
      string:
        type: string
    type: object
  domain.AccountBalance:
    properties:
      balance:
        type: number
    type: object
  domain.AccountCreatorRequest:
    properties:
      cpf:
        type: string
      name:
        type: string
      secret:
        type: string
    type: object
  domain.AccountCreatorResponse:
    properties:
      id:
        type: string
    type: object
  domain.AccountList:
    properties:
      accounts:
        items:
          $ref: '#/definitions/domain.Account'
        type: array
    type: object
  domain.JwtToken:
    properties:
      token:
        type: string
    type: object
  domain.Login:
    properties:
      cpf:
        type: string
      secret:
        type: string
    type: object
info:
  contact: {}
paths:
  /accounts:
    get:
      description: Return the list of all accounts. Fields 'secret' and 'balance'
        are omitted
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.AccountList'
      summary: Get accounts
      tags:
      - Account
    post:
      consumes:
      - application/json
      description: Create new Account in case 'cpf' doesn't exists yet
      parameters:
      - description: Account request
        in: body
        name: AccountRequest
        required: true
        schema:
          $ref: '#/definitions/domain.AccountCreatorRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.AccountCreatorResponse'
      summary: Create account
      tags:
      - Account
  /accounts/{account_id}/balance:
    get:
      description: Return account balance
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.AccountBalance'
      summary: Get account balance
      tags:
      - Account
  /login:
    post:
      consumes:
      - application/json
      description: Authemticate user
      parameters:
      - description: Login request
        in: body
        name: Login
        required: true
        schema:
          $ref: '#/definitions/domain.Login'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.JwtToken'
      summary: Login
      tags:
      - Login
swagger: "2.0"
