version: '3'
services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: greenbeans
      POSTGRES_DB: bank-transfer
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  go-bank-transfer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mynetwork

  migrate:
    image: migrate/migrate:v4.15.2
    profiles: ["tools"]
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://master:greenbeans@db:5432/bank-transfer?sslmode=disable",
      ]
    command: ["up"]
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork:

