// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: login_queries.sql

package queries

import (
	"context"
)

const createLogin = `-- name: CreateLogin :one
INSERT INTO logins(cpf, secret)
VALUES ($1, $2)
RETURNING cpf
`

type CreateLoginParams struct {
	Cpf    string
	Secret string
}

func (q *Queries) CreateLogin(ctx context.Context, arg CreateLoginParams) (string, error) {
	row := q.db.QueryRow(ctx, createLogin, arg.Cpf, arg.Secret)
	var cpf string
	err := row.Scan(&cpf)
	return cpf, err
}
