// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: transfers_queries.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers(id, account_origin_id, account_destination_id, amount)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateTransferParams struct {
	ID                   uuid.UUID
	AccountOriginID      uuid.UUID
	AccountDestinationID uuid.UUID
	Amount               int64
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.ID,
		arg.AccountOriginID,
		arg.AccountDestinationID,
		arg.Amount,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
